name: flutter_app
description: A new Flutter application.

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xterm:
    git: https://github.com/TerminalStudio/xterm.dart.git

  dartssh:
    git: https://github.com/GreenAppers/dartssh.git

  cupertino_icons: ^0.1.3

  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
