name: crossplatform_terminal
description: A new Flutter application.

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xterm:
    git: https://github.com/TerminalStudio/xterm.dart.git

  dartssh:
    git: https://github.com/GreenAppers/dartssh.git

  cupertino_icons: ^0.1.3

  websocket: ^0.0.5

  dio: ^3.0.10

  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
